# Basic Information 
title: "Wei Xue"
title2: "(薛玮/Xuē, Wěi)"
position: Ph.D. Student
affiliation: Radboud University
email: wei.xue (at) ru.nl

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Wei Xue, weixue, wei xue, WeiXue, XueWei, xuewei, Xue Wei, xue wei
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/

# Links 
# If you don't need one of them, you may delete the corresponding line.
researchgate: https://www.researchgate.net/profile/Wei-Xue-14
google_scholar: https://scholar.google.com/citations?user=35JJtlcAAAAJ&hl=en&inst=4701840609672088137
linkedin: https://www.linkedin.com/in/%E7%8E%AE-%E8%96%9B-817017130/


# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics


# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
